### ISSUE TITLE
Your experience designing microservices

### ISSUE THREAD

**Issue by knair99** [nurkiewicz/256#12]
# What would you like to cover?
How you feel about monolith vs microservices
When to embrace what architecture
As a startup, should you design microservices early?

# What is not worth mentioning?

# Any materials you recommend?

**Comment by nurkiewicz** [comment]
Thank you for your suggestion. I already did an [episode about microservices](https://256.nurkiewicz.com/36) - would you like to have something more to cover?

**Comment by knair99** [comment]
My bad, Tomasz. I hadn't gotten to this one before! This is exactly what I
was asking for.
