### ISSUE TITLE
WebSocket protocol

### ISSUE THREAD

**Issue by tarczynskitomek** [nurkiewicz/256#2]
# What would you like to cover?
- What's WebSocket anyways?
- The differences between WS and HTTP
- How the protocol negotiation happens between a client and a server?
- When to you use it?

# What is not worth mentioning?
- The good parts and bad parts - may be biased 

# Any materials you recommend?
- https://lucumr.pocoo.org/2012/9/24/websockets-101/ - pretty old article, but thorough explanations, and shorter than RFC ;-)

**Comment by nurkiewicz** [comment]
Great idea, thx!

**Comment by tarczynskitomek** [comment]
Inspired by the last podcast episode ;-)
