### ISSUE TITLE
REDIS

### ISSUE THREAD

**Issue by marceliwac** [nurkiewicz/256#3]
# What would you like to cover?
- Basic concept
- Benefits & disadvantages
- Use cases
- When not to use it

# What is not worth mentioning?
- Implementation details
- Prevalence

# Any materials you recommend?
_none_

**Comment by nurkiewicz** [comment]
Great idea, adding this to my backlog, probably sooner than later. I have 8 episodes in the pipeline right now, that'll go first.

**Comment by marceliwac** [comment]
@nurkiewicz Awesome! Thanks for that!

**Comment by nurkiewicz** [comment]
See https://256.nurkiewicz.com/31
