### ISSUE TITLE
Reactive programming

### ISSUE THREAD

**Issue by dhvl-nyk** [nurkiewicz/256#4]
# What would you like to cover?
Basic concept
Benefits & disadvantages
Use cases
When not to use it
Alternatives (Vert.x)

# What is not worth mentioning?
Implementation details

# Any materials you recommend?
https://projectreactor.io/

**Comment by nurkiewicz** [comment]
Thank you @dhvl-nyk, reactive programming is something I'm quite interested in, so I'll definitely cover it one day!

**Comment by nurkiewicz** [comment]
See https://256.nurkiewicz.com/35
